# Created with YamlCreate.ps1 v2.4.1 $debug=NVS1.CRLF.7-5-0-preview-5.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.PCManager
PackageVersion: 3.14.9.0
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.19042.0
InstallerType: msix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.WindowsAppRuntime.1.5
    MinimumVersion: 1.5.3
  ExternalDependencies:
  - Microsoft.EdgeWebView2Runtime
Scope: machine
UpgradeBehavior: install
PackageFamilyName: Microsoft.MicrosoftPCManager_8wekyb3d8bbwe
RestrictedCapabilities:
- localSystemServices
- packagedServices
- runFullTrust
- packageManagement
ElevationRequirement: elevationRequired
ReleaseDate: 2024-10-15
DisplayInstallWarnings: true
UnsupportedOSArchitectures:
- arm
- x86
Installers:
- Architecture: neutral
  InstallerUrl: https://dl.licaoz.com/mvp/PCManager/dists/msix/Microsoft.MicrosoftPCManager_3.14.9.0_neutral_~_8wekyb3d8bbwe.Msixbundle?sp=r&st=2024-10-01T00:00:00Z&se=2024-12-31T23:59:59Z&spr=https&sv=2022-11-02&sr=b&sig=R%2B2%2F6gCMH0KyZ%2BuymffJ3uhlpaUVz31UgT11ZrwhvOw%3D
  InstallerSha256: E47A34EF280B8CEBA075A4B65784A0B1311EEF20D60C60BCC8217F13F4125382
  SignatureSha256: 8757B6CE9A17FE8076348A727FA9EC16CA56A67819A2FC2C0A08E4F471F7C4E9
ManifestType: installer
ManifestVersion: 1.6.0
